"""
Disclaimer

This Kata is an insane step-up from Avanta's Kata, so I recommend to solve it first before trying this one.
Problem Description

A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

For example, different possibilities are:

Colour here:            G G        B G        R G        B R
Becomes colour here:     G          R          B          G

With a bigger example:

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G

You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would be given 'RRGBRGBB', and you should return 'G'.
Constraints

1 <= length(row) <= 10 ** 5

The input string will only contain the uppercase letters 'B', 'G' or 'R'.

The exact number of test cases will be as follows:

    100 tests of 100 <= length(row) <= 1000
    100 tests of 1000 <= length(row) <= 10000
    100 tests of 10000 <= length(row) <= 100000

Examples

triangle('B') == 'B'
triangle('GB') == 'R'
triangle('RRR') == 'R'
triangle('RGBG') == 'B'
triangle('RBRGBRB') == 'G'
triangle('RBRGBRBGGRRRBGBBBGG') == 'G'

"""

"""
From Paper: Soltions with length n = 3^s +1 where s is a positive integer are dependent only on start and end colour
"""
final_row = [2, 4, 10, 28, 82, 244, 730, 2188, 6562, 19684, 59050]
colours = {'R', 'G', 'B'}


def next(row):
    a = row[0]
    b = row[-1]
    if a == b:
        return a
    else:
        return (colours - {a, b}).pop()


def next3(row):
    new_row = ""
    for i in range(2):
        new_row += next(row[i]+row[i+1])
    return next(new_row)


def triangle(row):
    new_row = ""
    while len(row) > 1:
        for i in final_row[::-1]:
            if len(row) % i == 0:
                return next(row)
            elif len(row) == 3:
                return next3(row)
            if i < len(row):
                n = len(row)-i+1
                break

        new_row = triangle(row[0:n]) + triangle(row[n*-1:])
        row = new_row
        new_row = ""
    return row
